### PR TITLE
Readme.md - How to search with special characters

### PR DESCRIPTION
**Pull request by porg**

### CODE REVIEW

**Comment by porg** [comment]
Could you please accept my changes to the Readme?
That would help users with a common problem.

**Comment by arnemart** [comment]
Special characters should (and do, for me) work without enabling this setting – I'm Norwegian and I use special characters in searches every day, without any problems.

**Comment by porg** [comment]
I think it would be worth having this hint somewhere in the readme for those who experience character encoding issues (e.g. with an oddly configured server/service). If things are alright people do not consult the readme/manual anyways. But those who face issues can potentially be helped with.

You could rephrase it with "In the rare case that you experience… you may try …". That way it sheds no negative light on your extension. Rather shows great support value.

**Comment by porg** [comment]
Trust me I did NOT take the effort to write a Q&A for a fantasized/fabricated problem. But have concretely experienced it with Wikipedia, as evident on a screenshot posted in:

- #31

**Comment by porg** [comment]
"did NOT take the effort" - was what I had intended, should you only read that via email notification. Already fixed my typo in my previous comment. Will also delete this very comment in 5min after the notification has been sent out to you.

**Pull request closed without merging**
