### PR TITLE
Added step 4 to: Did the extension disappear… ?

### PR DESCRIPTION
**Pull request by porg**

### CODE REVIEW

**Comment by porg** [comment]
Could you please accept my changes to the Readme?
That would help users with a common problem.

**Comment by simonmichael** [comment]
Ping

**Comment by porg** [comment]
@simonmichael  thanks for supporting me in expediting the maintainer to accept my improvements in the readme.

**Comment by porg** [comment]
@arnemart What's the holdup in accepting my contribution?

**Comment by simonmichael** [comment]
PS, I pinged because I was checking activity in this repo and noticed several open issues this PR would help resolve. I just discovered this extremely useful extension and I'm very grateful for it. Thank you! If there was an easy sponsor button you'd have my money now.

**Comment by porg** [comment]
Dear plugin maintainer, please accept my README.md contribution contained in this pull request.

**Comment by arnemart** [comment]
Thank you for the PR, sorry I'm extremely slow in acknowledging it. I have slightly reworded your suggestion and will be pushing it momentarily.

**Pull request closed without merging**
